// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWWmf3b177VWY6ubWABDsscGuKkdZ-Lgc',
    appId: '1:197883232778:web:44402d099f8f4e821395f3',
    messagingSenderId: '197883232778',
    projectId: 'todo-app-5f050',
    authDomain: 'todo-app-5f050.firebaseapp.com',
    storageBucket: 'todo-app-5f050.appspot.com',
    measurementId: 'G-JE7Q3NEJ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23JihLfE61SCgh-CIOMdC7R8-cz3jvrQ',
    appId: '1:197883232778:android:1147e8cd96378d101395f3',
    messagingSenderId: '197883232778',
    projectId: 'todo-app-5f050',
    storageBucket: 'todo-app-5f050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfEqHMk12ffHp_SVf_ekabNLkYFAh7Mpw',
    appId: '1:197883232778:ios:9c42c1e4002846201395f3',
    messagingSenderId: '197883232778',
    projectId: 'todo-app-5f050',
    storageBucket: 'todo-app-5f050.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfEqHMk12ffHp_SVf_ekabNLkYFAh7Mpw',
    appId: '1:197883232778:ios:37701a548e42f5d11395f3',
    messagingSenderId: '197883232778',
    projectId: 'todo-app-5f050',
    storageBucket: 'todo-app-5f050.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
